### ISSUE TITLE
Need to be able to specify the lan_2_0 driver

### ISSUE THREAD

**Issue by xjparkerx** [logicminds/rubyipmi#25]
I am using rubyipmi through foreman for ipmi power operations.  I am able to successfully perform a power cycle on a Dell R720 via the iDRAC interface when using this command:
ipmipower -D LAN_2_0 -h hostname -u root -p <password> --stat

I configured my /etc/freeipmi.conf file to reflect the LAN_2_0 driver so that option will be passed every time ipmipower is ran but this still doesn't seem to help rubyipmi.

Any help would greatly be appreciated.
Justin

**Comment by logicminds** [comment]
Rubyipmi is supposed to figure this out automatically.  If this isn't happening let me know.
You can also supply the driver type manually if you want.

conn = Rubyipmi.connect(user,pass,host,'any',{:driver => 'lan20'})

https://github.com/logicminds/rubyipmi/blob/master/lib/rubyipmi/ipmitool/connection.rb#L30

**Comment by xjparkerx** [comment]
Thanks so much for the reply.  Do you have any suggestions of a way I can isolate the problem being Foreman or it being rubyipmi?

**Comment by logicminds** [comment]
First see if it works with Rubyipmi.

Try the following:

1. Install this gem `gem install rubyipmi`
2. run irb  (Ruby program)
3. enter the code in irb below

```
require 'rubyipmi'
conn = Rubyipmi.connect(user,pass,host)
conn.chassis.power.status
```
The more impi output you can provider the better code I can write.  I wrote this with only one server to test against and by luck it seems to work for others too.  Just be sure to remove any sensitive info.

**Comment by xjparkerx** [comment]
Awesome! Thanks so much for your help I am learning a lot!  I ran your test code and am getting a connection timeout error.

**Comment by logicminds** [comment]
what version of freeipmi are you using?  Also can you run

```ruby
require 'rubyipmi'
conn = Rubyipmi.connect(user,pass,host)
puts conn.inspect

```

**Comment by logicminds** [comment]
@xjparkerx what did you find out?  What kind of hardware are you using?  Is your impi device accessible on the network?

**Comment by logicminds** [comment]
Please see rubyipmi 0.9.0
