### ISSUE TITLE
ArgumentError: invalid byte sequence in UTF-8 for IBM MMI x3650 M4

### ISSUE THREAD

**Issue by buddwm** [logicminds/rubyipmi#38]
When I attempt to do a fru listing of an IBM x3650 M4, I get the following error:

    irb(main):004:0> conn.fru.list
    ArgumentError: invalid byte sequence in UTF-8
        from .rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubyipmi-0.10.0/lib/rubyipmi/freeipmi/commands/fru.rb:82:in `block in parse'
        from .rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubyipmi-0.10.0/lib/rubyipmi/freeipmi/commands/fru.rb:81:in `each'
        from .rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubyipmi-0.10.0/lib/rubyipmi/freeipmi/commands/fru.rb:81:in `parse'
        from .rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubyipmi-0.10.0/lib/rubyipmi/freeipmi/commands/fru.rb:53:in `list'

I'm using the following to connect to the system:

`conn = Rubyipmi.connect("username", "password", "ip address", "freeipmi", {:driver => "lan20"} )`

Oddly enough, if I run it again after the first attempt, it will return the expected values.

**Comment by logicminds** [comment]
what version of freeipmi are you using?  

Thanks for reporting.

**Comment by buddwm** [comment]
Currently using 1.4.11 in Ubuntu 16.04.

**Comment by buddwm** [comment]
I just realized that Ubuntu's package is a much older version.  If I manually install the latest version, 1.5.5, I don't see the issue.  May cause some confusion for those that use Ubuntu though.
