### ISSUE TITLE
need SOL functionality in rubyipmi

### ISSUE THREAD

**Issue by korekhov** [logicminds/rubyipmi#44]
I remember there were some conversations on supporting SOL in rubyipmi, but don't see anything coming out of that. Is this still on a radar?

I'd love to have this functionality, but because of interactive nature of this particular feature, I'd like to understand the limitations. Maybe at least an ability to open read-only sessions that a user can redirect to a file or something?

**Comment by logicminds** [comment]
Is this the same as #3

**Comment by korekhov** [comment]
Yes, it is. Closing this one as a duplicate.
