### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by ares** [logicminds/rubyipmi#50]
Could we please get a new release out? There's a patch fixing annoying issue causing deadlock https://github.com/ares/rubyipmi/commit/8c101921d2c5ac47f3077c6a0139f3fc1f8bb869 which was merged 4 years ago. No release since then :-( I'm happy to help with that if you give me permissions on the repo and at rubygems.org. Thanks.

**Comment by ares** [comment]
Oops, the right link to the fix is https://github.com/logicminds/rubyipmi/commit/8c101921d2c5ac47f3077c6a0139f3fc1f8bb869

**Comment by ekohl** [comment]
This is still needed. Foreman still depends on this gem so we certainly have an interest in this.

**Comment by lzap** [comment]
@logicminds I also volunteer for co-maintaining this gem.

**Comment by logicminds** [comment]
I just noticed this.  I have given access to @lzap.  I'll get a release out today.

**Comment by logicminds** [comment]
0.11.0 released.

https://rubygems.org/gems/rubyipmi

**Comment by ares** [comment]
awesome, thanks a lot!

**Comment by lzap** [comment]
Thank you!
